### ISSUE TITLE
Weak mobile test [ordering]

### ISSUE THREAD

**Issue by hsmett** [HybirdCorp/creme_crm#40]
See https://app.circleci.com/pipelines/github/HybirdCorp/creme_crm/159/workflows/38e5bc31-662b-4d9c-96f1-27a88a271353/jobs/622
`creme.mobile.tests.test_activities.MobileActivitiesTestCase.test_activities_portal01`
```
======================================================================
FAIL: test_activities_portal01 (creme.mobile.tests.test_activities.MobileActivitiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/circleci/project/creme/mobile/tests/test_activities.py", line 328, in test_activities_portal01
    self.assertEqual(expected_pcalls, pcalls)
  File "/usr/local/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.7/unittest/case.py", line 1058, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/lib/python3.7/unittest/case.py", line 1040, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [<Act[29 chars]call#1>, <Activity: Pcall#7>, <Activity: Pcall[130 chars]#14>] != [<Act[29 chars]call#7>, <Activity: Pcall#1>, <Activity: Pcall[130 chars]#14>]

First differing element 1:
<Activity: Pcall#1>
<Activity: Pcall#7>
  [<Activity: Pcall#2>,
+  <Activity: Pcall#7>,
   <Activity: Pcall#1>,
-  <Activity: Pcall#7>,
   <Activity: Pcall#8>,
   <Activity: Pcall#9>,
   <Activity: Pcall#10>,
   <Activity: Pcall#11>,
   <Activity: Pcall#12>,
   <Activity: Pcall#13>,
   <Activity: Pcall#14>]
```

**Comment by genglert** [comment]
Oh I fixed that one with the commit  https://github.com/HybirdCorp/creme_crm/commit/6a916a9a39ba5b2537894f1aa782d109f99f65c7
